export const ADMIN_GET_PRODUCT_TYPE_DETAILS = "ADMIN_GET_PRODUCT_TYPE_DETAILS";
export const ADMIN_GET_PRODUCT_TYPE_DETAILS_SUCCESS =
  "ADMIN_GET_PRODUCT_TYPE_DETAILS_SUCCESS";
export const ADMIN_GET_PRODUCT_TYPE_DETAILS_FAIL =
  "ADMIN_GET_PRODUCT_TYPE_DETAILS_FAIL";
