export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CATEGORY_PRODUCTS_DETAILS = "CATEGORY_PRODUCTS_DETAILS";
export const CATEGORY_PRODUCTS_DETAILS_SUCCESS =
  "CATEGORY_PRODUCTS_DETAILS_SUCCESS";
export const CATEGORY_PRODUCTS_DETAILS_FAIL = "CATEGORY_PRODUCTS_DETAILS_FAIL";

export const PRODUCT_CATEGORIES_DETAILS = "PRODUCT_CATEGORIES_DETAILS";
export const PRODUCT_CATEGORIES_DETAILS_SUCCESS =
  "PRODUCT_CATEGORIES_DETAILS_SUCCESS";
export const PRODUCT_CATEGORIES_DETAILS_FAIL =
  "PRODUCT_CATEGORIES_DETAILS_FAIL";

export const PRODUCT_SUB_CATEGORIES_DETAILS = "PRODUCT_SUB_CATEGORIES_DETAILS";
export const PRODUCT_SUB_CATEGORIES_DETAILS_SUCCESS =
  "PRODUCT_SUB_CATEGORIES_DETAILS_SUCCESS";
export const PRODUCT_SUB_CATEGORIES_DETAILS_FAIL =
  "PRODUCT_SUB_CATEGORIES_DETAILS_FAIL";

export const SUB_CATEGORY_PRODUCTS_DETAILS = "SUB_CATEGORY_PRODUCTS_DETAILS";
export const SUB_CATEGORY_PRODUCTS_DETAILS_SUCCESS =
  "SUB_CATEGORY_PRODUCTS_DETAILS_SUCCESS";
export const SUB_CATEGORY_PRODUCTS_DETAILS_FAIL =
  "SUB_CATEGORY_PRODUCTS_DETAILS_FAIL";
